### ISSUE TITLE
Au

### ISSUE THREAD

**Issue by Yonita34567** [byteverse/zigzag#5]
foo:
foo.SerializeAsString() == foo.SerializeAsString()
Hash(foo.SerializeAsString()) == Hash(foo.SerializeAsString())
CRC(foo.SerializeAsString()) == CRC(foo.SerializeAsString())
FingerPrint(foo.SerializeAsString()) == FingerPrint(foo.SerializeAsString())

**Comment by andrewthad** [comment]
Blocking the author for a month since this appears to be spam unrelated to this project.
